### ISSUE TITLE
Style on active filters

### ISSUE THREAD

**Issue by Calvein** [Calvein/humble-games#20]
Only works on Chrome right now, change the image for instance.

**Comment by Efreak** [comment]
[This](http://www.html5canvastutorials.com/advanced/html5-canvas-invert-image-colors-tutorial/) explains how to use canvas to invert an image, and you can see it in action at the bottom of the [Hoverizr](http://www.iliasiovis.com/hoverizr/) page; hoverizer code is [here](https://github.com/iliasiovis/Hoverizr/blob/master/jquery.hoverizr.js#L105).

**Comment by Calvein** [comment]
It was just a reminder to do something because of a lack of time. I'll just
put images.
