### ISSUE TITLE
Use JSON instead of a simple array

### ISSUE THREAD

**Issue by Efreak** [Calvein/humble-games#8]
I've converted the games.js to JSON over [here](https://github.com/Efreak/humble-games/), and populated it as well. I've implemented case-insensitive search in description, URL, developer, and game name (not just url now). I've also included the OS's available in the JSON, and whether or not it includes a soundtrack though I haven't implemented this kind of searching (and likely won't, as I'm too lazy to mess with the code that much). 

You can test out my changes [here](http://efreak.github.com/humble-games/)

I didn't want to submit a pull request for this, in case you don't want JSON (some other solution may be more feasible?)

**Comment by Calvein** [comment]
That's great, if you can push this to this repo I will add the possibility to sort by plateform & price.

**Comment by Efreak** [comment]
Awesome. I knew my time wouldn't be wasted :D
And on that note...When did github get emoji? :8ball: :cake:  :ear_of_rice:

**Comment by Calvein** [comment]
Since last year I think.
:arrow_right: http://www.emoji-cheat-sheet.com/
